In [1]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score
from numpy import asarray

In [2]:
from sklearn.datasets import make_multilabel_classification

In [3]:
features,target = make_multilabel_classification(n_samples=1000,n_features=10,n_classes=3,n_labels=2,random_state=12345)

In [4]:
print(features.shape, target.shape)

(1000, 10) (1000, 3)


In [5]:
for i in range(10):
    print(features[i], target[i])

[6. 4. 7. 2. 2. 9. 5. 3. 5. 7.] [0 0 0]
[1. 7. 4. 2. 9. 3. 1. 3. 3. 3.] [1 1 0]
[2. 8. 7. 0. 5. 5. 2. 8. 7. 6.] [1 1 1]
[ 5. 11. 10.  1. 11.  7.  7.  5.  3.  2.] [1 0 1]
[4. 7. 7. 0. 9. 9. 9. 6. 1. 0.] [1 0 0]
[3. 4. 4. 0. 9. 4. 7. 6. 3. 5.] [1 1 1]
[ 1.  9.  9.  0.  2.  4.  9. 11.  9.  0.] [1 0 0]
[9. 5. 6. 4. 6. 2. 4. 4. 7. 2.] [0 0 0]
[ 2.  9.  5.  0.  6. 11.  4.  3.  5.  1.] [1 0 0]
[ 2. 10.  9.  1.  7. 12.  6.  5. 10.  0.] [1 0 0]


In [6]:
n_inputs, n_outputs = features.shape[1], target.shape[1]

In [7]:
def get_model(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    model.add(Dense(n_outputs, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    return model

In [8]:
model = get_model(n_inputs, n_outputs)

In [9]:
model.fit(features,target, verbose=0, epochs=200)

In [10]:
new_pred = [3, 3, 6, 7, 8, 2, 11, 11, 1, 3]
newX = asarray([new_pred])
pred = model.predict(newX)
print('Predicted: %s' % pred[0])

Predicted: [0.00034785 0.00306252 0.00173995]
